<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2014.3.2.295
*/

require_once('form_process.php');

$form = array(
	'subject' => 'PUBLICATIONS Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'knava@nclr.org',
		'to' => 'knava@nclr.org'
	),
	'fields' => array(
		'custom_U4110' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Keyword search',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Keyword search\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'ISSUE AREA',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'ISSUE AREA\' is required.',
				'format' => 'Field \'ISSUE AREA\' has an invalid email.'
			)
		),
		'custom_U4099' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'PUBLICATION TYPE',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'PUBLICATION TYPE\' is required.'
			)
		),
		'custom_U4087' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'YEAR',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'YEAR\' is required.'
			)
		)
	)
);

process_form($form);
?>
